# Generated by Django 5.2.15 on 2026-06-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "attendance",
                    models.CharField(
                        choices=[
                            ("on_time", "حاضر في الوقت"),
                            ("late", "حاضر متأخر"),
                            ("absent_excused", "غائب بعذر"),
                            ("absent", "غائب"),
                        ],
                        max_length=20,
                        verbose_name="الحضور",
                    ),
                ),
                (
                    "interaction_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "رافض المشاركة"),
                            (2, "قليل الانسجام ويحرّك الفوضى"),
                            (3, "مشارك ومتوسط الأداء"),
                            (4, "مبادر ونشيط وساعد زملاءه"),
                            (5, "قائد نشيط يساعد زملاءه"),
                        ],
                        verbose_name="مستوى التفاعل والمشاركة",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("stable", "مستقر"),
                            ("anxious", "قلق"),
                            ("withdrawn", "منطوٍ"),
                            ("sad", "حزين ومنطوٍ"),
                            ("verbal_aggression", "عدواني لفظياً"),
                            ("physical_aggression", "عدواني جسدياً"),
                            ("agitated", "قلق ومتوتر"),
                        ],
                        max_length=30,
                        verbose_name="الحالة المزاجية",
                    ),
                ),
                (
                    "appearance",
                    models.CharField(
                        choices=[
                            ("excellent", "ملتزم بالزي الموحد ونظيف بالكامل"),
                            ("good", "ملتزم أو تبدو عليه علامات إهمال"),
                            ("poor", "غير ملتزم بالنظافة الشخصية"),
                        ],
                        max_length=20,
                        verbose_name="المظهر والنظافة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات عامة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المقيّم",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_assessments",
                        to="beneficiaries.beneficiary",
                        verbose_name="المستفيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم يومي",
                "verbose_name_plural": "التقييمات اليومية",
                "ordering": ["-date"],
                "unique_together": {("beneficiary", "date")},
            },
        ),
        migrations.CreateModel(
            name="RehabilitationIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_psychological_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="الطبي والنفسي",
                    ),
                ),
                (
                    "behavioral_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="السلوكي والانضباطي",
                    ),
                ),
                (
                    "skill_technical_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="المهاري والتقني",
                    ),
                ),
                (
                    "social_spiritual_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="الاجتماعي والروحي",
                    ),
                ),
                (
                    "medical_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        max_digits=5,
                        verbose_name="وزن الطبي",
                    ),
                ),
                (
                    "behavioral_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="وزن السلوكي",
                    ),
                ),
                (
                    "skill_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="وزن المهاري",
                    ),
                ),
                (
                    "social_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="وزن الاجتماعي",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="المؤشر الكلي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("progressing", "تقدّم مستقر"),
                            ("stable", "ثابت"),
                            ("regressing", "تراجع يحتاج تدخّل"),
                        ],
                        default="stable",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rehab_index",
                        to="assessments.dailyassessment",
                        verbose_name="التقييم اليومي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مؤشر التأهيل",
                "verbose_name_plural": "مؤشرات التأهيل",
            },
        ),
        migrations.CreateModel(
            name="ClinicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="البيانات")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="الدرجة"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="الدرجة القصوى",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="centers.clinic",
                        verbose_name="العيادة",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجّل",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_records",
                        to="assessments.dailyassessment",
                        verbose_name="التقييم اليومي",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل عيادة",
                "verbose_name_plural": "سجلات العيادات",
                "unique_together": {("assessment", "clinic")},
            },
        ),
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="البيانات")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="الدرجة"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="الدرجة القصوى",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="centers.activity",
                        verbose_name="النشاط",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجّل",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_records",
                        to="assessments.dailyassessment",
                        verbose_name="التقييم اليومي",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نشاط",
                "verbose_name_plural": "سجلات الأنشطة",
                "unique_together": {("assessment", "activity")},
            },
        ),
    ]
