# Generated by Django 5.2.15 on 2026-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrecord",
            name="max_score",
            field=models.FloatField(default=100, verbose_name="الدرجة القصوى"),
        ),
        migrations.AlterField(
            model_name="activityrecord",
            name="score",
            field=models.FloatField(default=0, verbose_name="الدرجة"),
        ),
        migrations.AlterField(
            model_name="clinicrecord",
            name="max_score",
            field=models.FloatField(default=100, verbose_name="الدرجة القصوى"),
        ),
        migrations.AlterField(
            model_name="clinicrecord",
            name="score",
            field=models.FloatField(default=0, verbose_name="الدرجة"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="behavioral_score",
            field=models.FloatField(default=0, verbose_name="السلوكي والانضباطي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="behavioral_weight",
            field=models.FloatField(default=20, verbose_name="وزن السلوكي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="medical_psychological_score",
            field=models.FloatField(default=0, verbose_name="الطبي والنفسي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="medical_weight",
            field=models.FloatField(default=40, verbose_name="وزن الطبي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="skill_technical_score",
            field=models.FloatField(default=0, verbose_name="المهاري والتقني"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="skill_weight",
            field=models.FloatField(default=20, verbose_name="وزن المهاري"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="social_spiritual_score",
            field=models.FloatField(default=0, verbose_name="الاجتماعي والروحي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="social_weight",
            field=models.FloatField(default=20, verbose_name="وزن الاجتماعي"),
        ),
        migrations.AlterField(
            model_name="rehabilitationindex",
            name="total_score",
            field=models.FloatField(default=0, verbose_name="المؤشر الكلي"),
        ),
    ]
