# Generated by Django 5.2.15 on 2026-06-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_activityrecord_max_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyassessment",
            name="appearance",
        ),
        migrations.RemoveField(
            model_name="dailyassessment",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="dailyassessment",
            name="interaction_level",
        ),
        migrations.RemoveField(
            model_name="dailyassessment",
            name="mood",
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="behavioral_score",
            field=models.FloatField(default=0, verbose_name="درجة الحالة العامة"),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="general_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="بيانات الحالة العامة"
            ),
        ),
        migrations.AlterField(
            model_name="dailyassessment",
            name="assessed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
    ]
