# Generated by Django 5.2.15 on 2026-06-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="الرقم المرجعي"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=300, verbose_name="الاسم الكامل"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الهوية"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="جهة اتصال الطوارئ"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف الطوارئ"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                ("admission_date", models.DateField(verbose_name="تاريخ الدخول")),
                (
                    "expected_discharge_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج المتوقع"
                    ),
                ),
                (
                    "actual_discharge_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الخروج الفعلي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("discharged", "خرج"),
                            ("suspended", "معلّق"),
                            ("transferred", "محوّل"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "admission_reason",
                    models.TextField(blank=True, verbose_name="سبب الدخول"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="beneficiaries/photos/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستفيد",
                "verbose_name_plural": "المستفيدون",
                "ordering": ["-admission_date", "full_name"],
            },
        ),
    ]
