# Generated by Django 5.2.15 on 2026-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("centers", "0003_generalfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_activities",
            field=models.ManyToManyField(
                blank=True,
                help_text="عيّن أنشطة محددة لمسؤول النشاط؛ اتركها فارغة لمنح صلاحية المركز بالكامل",
                to="centers.activity",
                verbose_name="الأنشطة المعيّنة",
            ),
        ),
    ]
