# Generated by Django 5.2.15 on 2026-06-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="اسم المركز"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="المعرّف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "icon",
                    models.CharField(
                        default="bi-building", max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="اللون"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="النسبة المئوية لوزن هذا المركز في حساب مؤشر التأهيل اليومي",
                        max_digits=5,
                        verbose_name="الوزن في مؤشر التأهيل",
                    ),
                ),
                (
                    "axis",
                    models.CharField(
                        choices=[
                            ("medical_psychological", "المحور الطبي والنفسي"),
                            ("behavioral", "المحور السلوكي والانضباطي"),
                            ("skill_technical", "المحور المهاري والتقني"),
                            ("social_spiritual", "المحور الاجتماعي والروحي"),
                        ],
                        default="skill_technical",
                        max_length=50,
                        verbose_name="المحور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مركز",
                "verbose_name_plural": "المراكز",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم النشاط")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=200, verbose_name="المعرّف"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="centers.center",
                        verbose_name="المركز",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط",
                "verbose_name_plural": "الأنشطة",
                "ordering": ["order", "name"],
                "unique_together": {("center", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم العيادة")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=200, verbose_name="المعرّف"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinics",
                        to="centers.center",
                        verbose_name="المركز",
                    ),
                ),
            ],
            options={
                "verbose_name": "عيادة",
                "verbose_name_plural": "العيادات",
                "ordering": ["order", "name"],
                "unique_together": {("center", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ActivityField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحقل")),
                (
                    "field_key",
                    models.SlugField(
                        allow_unicode=True, max_length=200, verbose_name="مفتاح الحقل"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("number", "رقم"),
                            ("rating", "تقييم (1-5)"),
                            ("rating10", "تقييم (1-10)"),
                            ("boolean", "نعم/لا"),
                            ("choice", "اختيار"),
                            ("date", "تاريخ"),
                            ("time", "وقت"),
                            ("textarea", "نص طويل"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحقل",
                    ),
                ),
                (
                    "choices_text",
                    models.TextField(
                        blank=True,
                        help_text="خيار واحد في كل سطر (لنوع الاختيار)",
                        verbose_name="الخيارات",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="مطلوب"),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="الدرجة القصوى",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="centers.activity",
                        verbose_name="النشاط",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقل النشاط",
                "verbose_name_plural": "حقول الأنشطة",
                "ordering": ["order"],
                "unique_together": {("activity", "field_key")},
            },
        ),
        migrations.CreateModel(
            name="ClinicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحقل")),
                (
                    "field_key",
                    models.SlugField(
                        allow_unicode=True, max_length=200, verbose_name="مفتاح الحقل"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("number", "رقم"),
                            ("rating", "تقييم (1-5)"),
                            ("rating10", "تقييم (1-10)"),
                            ("boolean", "نعم/لا"),
                            ("choice", "اختيار"),
                            ("date", "تاريخ"),
                            ("time", "وقت"),
                            ("textarea", "نص طويل"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحقل",
                    ),
                ),
                (
                    "choices_text",
                    models.TextField(
                        blank=True,
                        help_text="خيار واحد في كل سطر",
                        verbose_name="الخيارات",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="مطلوب"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="مثل: ملم زئبق، كغم، °م",
                        max_length=50,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "normal_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأدنى الطبيعي",
                    ),
                ),
                (
                    "normal_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأعلى الطبيعي",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="centers.clinic",
                        verbose_name="العيادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقل العيادة",
                "verbose_name_plural": "حقول العيادات",
                "ordering": ["order"],
                "unique_together": {("clinic", "field_key")},
            },
        ),
    ]
