# Generated by Django 5.2.15 on 2026-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityfield",
            name="max_score",
            field=models.FloatField(default=5, verbose_name="الدرجة القصوى"),
        ),
        migrations.AlterField(
            model_name="center",
            name="weight",
            field=models.FloatField(
                default=0,
                help_text="النسبة المئوية لوزن هذا المركز في حساب مؤشر التأهيل اليومي",
                verbose_name="الوزن في مؤشر التأهيل",
            ),
        ),
        migrations.AlterField(
            model_name="clinicfield",
            name="normal_max",
            field=models.FloatField(
                blank=True, null=True, verbose_name="الحد الأعلى الطبيعي"
            ),
        ),
        migrations.AlterField(
            model_name="clinicfield",
            name="normal_min",
            field=models.FloatField(
                blank=True, null=True, verbose_name="الحد الأدنى الطبيعي"
            ),
        ),
    ]
