# Generated by Django 5.2.15 on 2026-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_alter_activityfield_max_score_alter_center_weight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحقل")),
                (
                    "field_key",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="مفتاح الحقل",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("number", "رقم"),
                            ("rating", "تقييم (1-5)"),
                            ("rating10", "تقييم (1-10)"),
                            ("boolean", "نعم/لا"),
                            ("choice", "اختيار"),
                            ("date", "تاريخ"),
                            ("time", "وقت"),
                            ("textarea", "نص طويل"),
                        ],
                        default="rating",
                        max_length=20,
                        verbose_name="نوع الحقل",
                    ),
                ),
                (
                    "choices_text",
                    models.TextField(
                        blank=True,
                        help_text="خيار واحد في كل سطر (لنوع الاختيار)",
                        verbose_name="الخيارات",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="مطلوب"),
                ),
                (
                    "max_score",
                    models.FloatField(
                        default=5,
                        help_text="تُستخدم في حساب المحور السلوكي",
                        verbose_name="الدرجة القصوى",
                    ),
                ),
                (
                    "counts_in_score",
                    models.BooleanField(
                        default=True, verbose_name="يُحتسب في المؤشر السلوكي"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "حقل عام",
                "verbose_name_plural": "الحقول العامة للاستمارة",
                "ordering": ["order", "name"],
            },
        ),
    ]
